---
- name: SQL Server Health Check on Windows using Ansible
  hosts: sql_servers
  gather_facts: no
  tasks:

    - name: Check database space utilization
      ansible.builtin.shell: |
        sqlcmd -S {{ sql_server }} -U {{ sql_username }} -P {{ sql_password }} -Q "
        SELECT DB_NAME(database_id) AS DatabaseName, SUM(size * 8) / 1024 AS TotalSizeMB 
        FROM sys.master_files GROUP BY database_id;"
      register: db_space_result

    - debug:
        msg: "{{ db_space_result.stdout_lines }}"

    - name: Check for deadlocks
      ansible.builtin.shell: |
        sqlcmd -S {{ sql_server }} -U {{ sql_username }} -P {{ sql_password }} -Q "
        SELECT * FROM sys.dm_tran_locks WHERE request_status = 'WAIT';"
      register: deadlock_result

    - debug:
        msg: "{{ deadlock_result.stdout_lines }}"

    - name: Check SQL Server Agent job activities
      ansible.builtin.shell: |
        sqlcmd -S {{ sql_server }} -U {{ sql_username }} -P {{ sql_password }} -Q "
        SELECT j.name, j.enabled, MAX(h.run_status) AS last_run_status
        FROM msdb.dbo.sysjobs j
        LEFT JOIN msdb.dbo.sysjobhistory h ON j.job_id = h.job_id
        WHERE h.step_id = 0
        GROUP BY j.name, j.enabled;"
      register: job_result

    - debug:
        msg: "{{ job_result.stdout_lines }}"

    - name: Check SQL Server health
      ansible.builtin.shell: |
        sqlcmd -S {{ sql_server }} -U {{ sql_username }} -P {{ sql_password }} -Q "
        SELECT name AS DatabaseName, state_desc AS Status FROM sys.databases;"
      register: health_result

    - debug:
        msg: "{{ health_result.stdout_lines }}"
